version: '3'

services:
  cobble-nginx:
    container_name: cobble-nginx
    build:
      dockerfile: docker/nginx/Dockerfile
      context: .
      target: dev
    working_dir: /application
    ports:
      - 8001:80
    restart: on-failure
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/application:delegated
    depends_on:
      - cobble-fpm
      - cobble-mysql8

  cobble-fpm:
    container_name: cobble-fpm
    build:
      dockerfile: docker/php-fpm/Dockerfile
      context: .
      target: dev
    restart: on-failure
    volumes:
      - .:/application:delegated
      - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
      - ~/.ssh/:/root/.ssh/
    working_dir: /application
    depends_on:
      - cobble-mysql8

  cobble-mysql8:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    container_name: cobble-mysql8
    restart: unless-stopped
    ports:
      - '8878:3306'
    environment:
      MYSQL_USER: 'db_user'
      MYSQL_PASSWORD: '123456'
      MYSQL_ROOT_PASSWORD: '123456'
    volumes:
      - './docker/data/mysql8:/var/lib/mysql'
      - './docker/sql/:/docker-entrypoint-initdb.d'
